substitutions:
    _REGION: asia-northeast1
    _ARTIFACT_REPO_NAME: team2021
    _MODE: staging

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - 'build'
    - '-t'
    - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/webserver:$BRANCH_NAME'
    - '--build-arg'
    - 'MODE=$_MODE'
    - '.'
    timeout: 300s
  - name: 'gcr.io/cloud-builders/docker'
    args: 
    - 'push'
    - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/webserver:$BRANCH_NAME'
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'webserver-$_ARTIFACT_REPO_NAME-$BRANCH_NAME'
      - '--image'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REPO_NAME/webserver:$BRANCH_NAME'
      - '--region'
      - '$_REGION'
      - '--platform'
      - 'managed'

